# @package __global__

data:
  motion_loader:
    _target_: src.data.g1_motion.G1MotionLoader
    base_dir: F:/HumanML3D_G1/unitreeg1/new_joint_vecs_v4
    fps: 20.0
    disable: false
    nfeats: 363
    umin_s: 0.5
    umax_s: 3.0
