resume_dir: null
ckpt: last

run_dir: outputs_g1/frankenbot_clip_part_g1_g1_joints_g1-frankenstein
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 8

dataset: g1-frankenstein

seed: 1234
logger_level: INFO
device: cuda

data:
  _target_: src.data.text_motion.TextMotionDataset_Part
  name: ${dataset}
  split: train
  min_seconds: 1.0
  max_seconds: 20.0
  preload: true
  tiny: false
  drop_motion_perc: 0
  drop_cond: 0.1
  drop_trans: 0
  condition: t2m
  annotation: annotations.json

  motion_loader:
    _target_: src.data.g1_motion.G1MotionLoader
    base_dir: /mnt/data/g1_data/new_joint_vecs_v4
    fps: 20.0
    disable: false
    nfeats: 363
    umin_s: 0.5
    umax_s: 3.0

  text_encoder:
    _target_: src.data.text_part.TextEmbeddings
    base_dir: datasets/annotations/g1-frankenstein/text_embeddings
    dataname: g1-frankenstein
    modelname: clip
    device: cuda
    preload: true
    mean_pooling: false
    disable: false
    nfeats: 512
    pca: 51
    fps: 20.0
    body_part_order: ["action", "trajectory", "spine", "head", "left_arm", "right_arm", "left_leg", "right_leg"]
    load_global: true
    load_global_type: caption
    rand_mask: true
    mask_ratio: 0.5
    no_model: True

diffusion:
  _target_: src.model.gaussian.GaussianDiffusion
  g_text: True
  loss_type: WeightedMSE

  denoiser:
    _target_: src.model.backbones.frankenmotion.TransformerDenoiser
    nfeats: 771
    tx_dim: 512
    latent_dim: 512
    ff_size: 2048
    num_layers: 4
    num_heads: 8
    dropout: 0.1
    activation: gelu
    nb_registers: 0

  schedule:
    _target_: src.model.schedule.cosine.CosineBetaSchedule
    s: 0.008

  motion_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: ${run_dir}/motion_stats
    eps: 1e-12

  text_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: ${run_dir}/text_stats
    eps: 1e-12

  timesteps: 100
  prediction: x
  lr: 1e-4

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 6000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      every_n_epochs: 1
      save_top_k: 1
      save_last: true
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      monitor: step
      mode: max
      every_n_epochs: 500
      save_top_k: -1
      save_last: false
    - _target_: src.callback.progress.ProgressLogger
      precision: 3
    - _target_: src.callback.tqdmbar.TQDMProgressBar
  logger:
    - _target_: pytorch_lightning.loggers.WandbLogger
      save_dir: ${run_dir}
      name: ${run_dir}
      project: FrankenG1
    - _target_: src.logger.csv.CSVLogger
      save_dir: ${run_dir}
      name: logs
