resume_dir: null
ckpt: last

motion_features: ${hydra:runtime.choices.motion_loader}
text_features: ${hydra:runtime.choices.text_encoder}

run_dir: outputs_g1/frankenbot_${text_features}_${motion_features}_${dataset}${run_suffix}
run_suffix: ""

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 8

dataset: g1-frankenstein

defaults:
  - text_encoder: clip_part_g1
  - motion_loader: g1_joints
  - frankenbot
  - trainer
  - defaults
  - _self_

data:
  motion_loader: ${motion_loader}
  text_encoder:
    no_model: True
